name: nutrihummingbird
display_name: Nutri Hummingbird
version: 1.0.0
author:
  name: "Nutriweb"
  email: ""
  url: ""

meta:
  compatibility:
    from: 8.0.0
  available_layouts:
    layout-full-width:
      name: Full width layout
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three columns layout
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two columns, small right column
      description: Two columns with a small right column

# Parent theme inheritance
parent: hummingbird

# Assets configuration
assets:
  use_parent_assets: true

# Global settings
global_settings:
  configuration:
    PS_IMAGE_QUALITY: jpg
